
mod "stdlib",   :git => "https://github.com/puppetlabs/puppetlabs-stdlib",  :ref => "4.3.2"
mod "concat",   :git => "https://github.com/puppetlabs/puppetlabs-concat",  :ref => "1.1.0"
mod "vcsrepo",  :git => "https://github.com/puppetlabs/puppetlabs-vcsrepo", :ref => "1.1.0"
mod "java",     :git => "https://github.com/puppetlabs/puppetlabs-java",    :ref => "1.2.0"
mod "mysql",    :git => "https://github.com/puppetlabs/puppetlabs-mysql",   :ref => "3.1.0"
mod "tomcat",   :git => "https://github.com/puppetlabs/puppetlabs-tomcat",  :ref => "1.2.0"
mod "apt",      :git => "https://github.com/puppetlabs/puppetlabs-apt.git", :ref => "1.7.0"

mod "nginx",    :git => "https://github.com/jfryman/puppet-nginx",          :ref => "0.2.1"
mod "htpasswd", :git => "https://github.com/leinaddm/puppet-htpasswd",      :ref => "v0.0.3"
mod "maven",    :git => "https://github.com/maestrodev/puppet-maven",       :ref => "v1.4.0"
mod "wget",     :git => "https://github.com/maestrodev/puppet-wget",        :ref => "v1.5.7"
mod "staging",  :git => "https://github.com/nanliu/puppet-staging",         :ref => "1.0.4"

